config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'get_location_info' => 'meetings#get_location_info'
  get 'meetings' => 'meetings#new'
  get 'home/index'
  get 'home/index1'
  post '/home/index1' => 'home#index1'
  get 'home/hospital'
  get 'home/detail'
  get 'home/growth'
  
  get '/home/update/:user_id' => 'home#update'
  get '/home/edit/:user_id' => 'home#edit'
  post '/home/edit/:user_id' => 'home#edit'
  
  get '/home/ranking/:category_id' => 'home#detail'
  get '/home/ranking/:category_id/:ranking_num' => 'home#keyworddetail'
  

  root 'home#index1'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
    belongs_to :User
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
  require '~/Supermom-Front/lib/naver_crawler.rb'
  def get_location_info
    require 'rubygems'
    require 'mechanize'
    require 'rest-client' 

    festival_date = []
    festival_name = []
    search_arr = ['축제', '베이비페어']
    @n_c = Naver_cralwer.new
    proxies = @n_c.create_proxy

    search_arr.each do | search |
      agent = Mechanize.new
      proxies.each do |proxy|
	if @n_c.check_vaild_proxy("http://naver.com",proxy)
		agent.set_proxy(proxy.addr,proxy.port)
		break;
        end
      end
  
      page = agent.get "http://naver.com"
      search_form = page.form_with :name => "sform"
      search_form.field_with(:name=>"query").value = search
      search_results = agent.submit search_form
      main_uri = search_results.uri

      html = agent.get(main_uri).body
      html_doc = Nokogiri::HTML(html)
      
      html_doc.css('span.tit_box').css('span.date').each do |t|
          festival_date <<  t.text.slice!(0...10).gsub('.','-')
        end 

        if search.eql?('축제')
          html_doc.css('h5').each do |t|
            festival_name << t.text
          end
        else
          html_doc.css('h6').each do |t|
            festival_name << t.text
          end
        end
    end
    
    for i in 0..festival_name.length-1
      @meeting = Meeting.new
      @meeting.name = festival_name[i]
      @meeting.start_time = DateTime.strptime(festival_date[i], "%Y-%m-%d")
      @meeting.save
    end
    
    redirect_to '/meetings'
  end

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
    # get_location_info
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
       if @meeting.save
        # format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        # format.json { render :index, status: :created, location: @meeting }
        format.html { redirect_to meetings_url}
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        # format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        # format.json { render :show, status: :ok, location: @meeting }
        format.html { redirect_to meetings_url, notice: @meeting.start_time.in_time_zone("Asia/Seoul").strftime("%F")+' 이벤트가 성공적으로 갱신되었습니다.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit class: "btn btn-primary btn-block btn-flat" %>
  </div>
<% end %>

<br>

app/views/meetings/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>MoMCARE | MeetingEdit</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
 
</head>



<body class="hold-transition skin-blue sidebar-mini">


  <div class="control-sidebar-bg"></div>

<p id="notice"><%= notice %></p>

<div class="register-box">
  <div class="register-logo">
    <a href="/">Editing Meeting</a>
  </div>

  <div class="register-box-body">
    <p class="login-box-msg">이벤트를 수정해주세요</p>
    
    <%= render 'form' %>

    <%= link_to 'Show', @meeting %> |
    <%= link_to 'Back', meetings_path %>
  </div>
</div>

<div class="container" align="center">
      <!--<h1>Editing Meeting</h1>-->
    
    <%#= render 'form' %>
    
    <%#= link_to 'Show', @meeting %> |
    <%#= link_to 'Back', meetings_path %>

</div>
<br>



</body>



</body>
</html>

app/views/meetings/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>MoMCARE | Calendar</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
        <style>
          
          /* line 2, /usr/local/rvm/gems/ruby-2.3.4/gems/simple_calendar-2.2.6/app/assets/stylesheets/simple_calendar.scss */
          .simple-calendar table {
            -webkit-border-horizontal-spacing: 0px;
            -webkit-border-vertical-spacing: 0px;
            background-color: #ffffff;
            border: 1px solid #dddddd;
            border-collapse: collapse;
            box-sizing: border-box;
            max-width: 100%;
            width: 100%;
          }
          /* line 13, /usr/local/rvm/gems/ruby-2.3.4/gems/simple_calendar-2.2.6/app/assets/stylesheets/simple_calendar.scss */
          .simple-calendar tr {
            border-collapse: collapse;
          }
          /* line 17, /usr/local/rvm/gems/ruby-2.3.4/gems/simple_calendar-2.2.6/app/assets/stylesheets/simple_calendar.scss */
          .simple-calendar th {
            padding: 6px;
            border-bottom: 2px solid #dddddd;
            border-collapse: collapse;
            border-left: 1px solid #dddddd;
            border-right: 1px solid #dddddd;
            border-top: 0px none #333333;
            box-sizing: border-box;
            text-align: left;
          }
          /* line 28, /usr/local/rvm/gems/ruby-2.3.4/gems/simple_calendar-2.2.6/app/assets/stylesheets/simple_calendar.scss */
          .simple-calendar td {
            padding: 6px;
            vertical-align: top;
            width: 14%;
            border: 1px solid #ddd;
            border-top-color: #dddddd;
            border-top-style: solid;
            border-top-width: 1px;
            border-right-color: #dddddd;
            border-right-style: solid;
            border-right-width: 1px;
            border-bottom-color: #dddddd;
            border-bottom-style: solid;
            border-bottom-width: 1px;
            border-left-color: #dddddd;
            border-left-style: solid;
            border-left-width: 1px;
          }
          /* line 48, /usr/local/rvm/gems/ruby-2.3.4/gems/simple_calendar-2.2.6/app/assets/stylesheets/simple_calendar.scss */
          .simple-calendar .day {
            height: 80px;
          }
          /* line 60, /usr/local/rvm/gems/ruby-2.3.4/gems/simple_calendar-2.2.6/app/assets/stylesheets/simple_calendar.scss */
          .simple-calendar .today {
            font-weight:bold;
            background-color: #beccf5;
          }
          /* line 69, /usr/local/rvm/gems/ruby-2.3.4/gems/simple_calendar-2.2.6/app/assets/stylesheets/simple_calendar.scss */
          .simple-calendar .prev-month {
            color:#bdbbbb;
          }
          /* line 72, /usr/local/rvm/gems/ruby-2.3.4/gems/simple_calendar-2.2.6/app/assets/stylesheets/simple_calendar.scss */
          .simple-calendar .next-month {
            color:#bdbbbb;
          }

          .has-events div {
            background: #ffd5d5;
            /*font-weight:bold;*/
          }
          .calendar-heading {
              text-align:center;
              font-size:30px;
              font-weight:bold;
              margin-bottom:15px;
              color: #FFA500;
          }
        </style>
</head>
<body class="hold-transition skin-blue sidebar-mini">

  <div class="control-sidebar-bg"></div>

<p id="notice"><%= notice %></p>

<div class="container" align="center">
  <span class="logo-lg" style="font-size:40px"><b>EVENT CALENDAR</b></span><br>
  <%= link_to 'NEW EVENT', new_meeting_path,style: "color:#fff; background:#ff6464; border:0px;vertical-align: middle; margin-bottom:20px; margin-left:10px", class:"menuLink btn btn-primary" %>
  <a href="get_location_info" style="color:#fff; background:#ff6464; border:0px;vertical-align: middle; margin-bottom:20px; margin-left:10px" class="menuLink btn btn-primary">GET FESTIVAL INFO</a>


<%= month_calendar events: @meetings do |date, meetings| %>
     <%= date.day %>
      <% meetings.each do |meeting| %>
        <div>
          <%= meeting.name %><br>
          <div class="btn-group">
          <div class="pull-left">
            <%#= link_to 'Edit', edit_meeting_path(meeting), style: "color:#fff; background:#ff6464; border:0px;vertical-align: middle; margin-bottom:20px; margin-left:10px"%>
            <%= button_to 'Edit', edit_meeting_path(meeting), style: "color:#fff; background:#ff6464; border:0px;vertical-align: middle; margin-bottom:20px; margin-left:10px", :method => :get%>
          </div>
          <div class="pull-left">
            <%= button_to 'Destroy', meeting, method: :delete, data: { confirm: "Are you sure?" }, style: "color:#fff; background:#ff6464; border:0px;vertical-align: middle; margin-bottom:20px; margin-left:10px" %>
            <%#= link_to 'Delete',meeting,:method => :delete,:confirm => 'Are you sure you want to delete this item?' %>
          </div>
          </div>
        </div>
      <% end %>
    <% end %>

</div>
<br>

</body>
</html>

app/views/meetings/new.html.erb
<p id="notice"><%= notice %></p>

<div class="register-box">
  <div class="register-logo">
    <a href="/">New Meeting</a>
  </div>

  <div class="register-box-body">
    <p class="login-box-msg">새로운 이벤트를 등록해주세요</p>
    
    <%= render 'form' %>

    <%= link_to 'Back', meetings_path %>
  </div>
</div>

app/views/meetings/show.html.erb
<<<<<<< HEAD
=======
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>MoMCARE | Calendar</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="/bower_components/Ionicons/css/ionicons.min.css">
  <!-- fullCalendar -->
  <link rel="stylesheet" href="/bower_components/fullcalendar/dist/fullcalendar.min.css">
  <link rel="stylesheet" href="/bower_components/fullcalendar/dist/fullcalendar.print.min.css" media="print">
  <!-- Theme style -->
  <link rel="stylesheet" href="/dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="/dist/css/skins/_all-skins.min.css">

  <!-- Google Font -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        
</head>
<body class="hold-transition skin-blue sidebar-mini">

  <div class="control-sidebar-bg"></div>

>>>>>>> 5aaf83e15c6a972826c71fafcaf4c31a72ede319
<p id="notice"><%= notice %></p>

<div class="container" align="center">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @meeting.name %>
  </p>
  
  <p>
    <strong>Start time:</strong>
    <%= @meeting.start_time %>
  </p>
  
  <%= link_to 'Edit', edit_meeting_path(@meeting) %> |
  <%= link_to 'Back', meetings_path %>

</div>
<<<<<<< HEAD
<br>
=======
<br>



<!-- jQuery 3 -->
<script src="/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="/bower_components/jquery-ui/jquery-ui.min.js"></script>
<!-- Slimscroll -->
<script src="/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="/bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="/dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/dist/js/demo.js"></script>
<!-- fullCalendar -->
<script src="/bower_components/moment/moment.js"></script>
<script src="/bower_components/fullcalendar/dist/fullcalendar.min.js"></script>
<!-- Page specific script -->

</body>
</html>
>>>>>>> 5aaf83e15c6a972826c71fafcaf4c31a72ede319